# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]

repos:
  # Pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: |
          (?x)(
              ^CMakeLists.txt|
              ^src/CMakeLists.txt
              |^test/CMakeLists.txt
              |^cmake/
          )
      - id: mixed-line-ending
        args: [--fix=no]
      - id: no-commit-to-branch
        args: [-b, main, -p, release.*]
      - id: pretty-format-json
        args: [--autofix, --indent, "4"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        types_or: [c++, c]
        args: [ --dry-run, -Werror]
    # Camke Format
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    - id: cmake-format
    #- id: cmake-lint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.3.0
    hooks:
      - id: codespell
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
  # Commit-msg hooks
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
